# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=32)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('signin_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=256)),
                ('code_expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=256)),
                ('token_expire_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
